#spring:
#  application:
#    name: ms-dicvoery
#
#server:
#  port: 8772
#
#eureka:
#  instance:
#    hostname: ms-discovery2
#    prefer-ip-address: true
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://user:password@ms-discovery1:8771/eureka/
#
