spring:
  application:
    name: ms-dicvoery
#  profiles:
#    active: local

server:
  port: 8761

eureka:
  instance:
    hostname: ms-dicvoery
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password@${eureka.instance.hostname}:${server.port}/eureka/
